#!/usr/bin/env python3
"""Version management helper — called by build_exe.ps1.

Reads version.json, applies the requested version bump, writes version.json
and app/_version.py, then prints the resulting metadata as a JSON line that
the PowerShell script can consume with ConvertFrom-Json.

Usage (called by build_exe.ps1, not directly)::

    python build_version.py                  # DEV build
    python build_version.py --release-revision
    python build_version.py --release-minor
    python build_version.py --release-major
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def _git_short_hash() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except Exception:
        return "unknown"


def main() -> None:
    p = argparse.ArgumentParser(description="Logger Speed version manager")
    grp = p.add_mutually_exclusive_group()
    grp.add_argument("--release-revision", action="store_true",
                     help="Bump x.y.Z — bug-fix release")
    grp.add_argument("--release-minor",    action="store_true",
                     help="Bump x.Y.0 — new features")
    grp.add_argument("--release-major",    action="store_true",
                     help="Bump X.0.0 — breaking changes")
    args = p.parse_args()

    # ── Read current version ────────────────────────────────────────────────────
    # utf-8-sig handles the UTF-8 BOM that PowerShell 5 adds when writing files
    v = json.loads((ROOT / "version.json").read_text(encoding="utf-8-sig"))
    major    = int(v["major"])
    minor    = int(v["minor"])
    revision = int(v["revision"])
    build    = int(v["build"])

    # ── Apply bump ──────────────────────────────────────────────────────────────
    is_release = False
    if args.release_major:
        major += 1;  minor = 0;    revision = 0; build = 0; is_release = True
    elif args.release_minor:
        minor += 1;  revision = 0; build = 0;                is_release = True
    elif args.release_revision:
        revision += 1; build = 0;                            is_release = True
    else:
        build += 1  # DEV: only increment build counter

    is_dev   = not is_release
    version  = f"{major}.{minor}.{revision}"
    commit   = _git_short_hash()

    # ── Compute display strings ─────────────────────────────────────────────────
    if is_dev:
        full_version = f"DEV {version} build {build}"
        exe_name     = f"LoggerSpeed_DEV_{version}_build{build}"
    else:
        full_version = version
        exe_name     = f"LoggerSpeed_{version}"

    # ── Write version.json ──────────────────────────────────────────────────────
    new_v: dict = {
        "major":    major,
        "minor":    minor,
        "revision": revision,
        "build":    build,
        "commit":   commit,
        "is_dev":   is_dev,
    }
    (ROOT / "version.json").write_text(
        json.dumps(new_v, indent=4), encoding="utf-8"
    )

    # ── Write app/_version.py (baked into the exe by PyInstaller) ──────────────
    py_lines = [
        "# AUTO-GENERATED by build_exe.ps1 -- do not edit manually.",
        f'# Built: {full_version}  commit {commit}',
        f'VERSION = "{version}"',
        f"BUILD = {build}",
        f'COMMIT = "{commit}"',
        f"IS_DEV = {is_dev}",
        f'FULL_VERSION = "{full_version}"',
        "",
    ]
    (ROOT / "app" / "_version.py").write_text(
        "\n".join(py_lines), encoding="utf-8"
    )

    # ── Output result for PowerShell to consume (ConvertFrom-Json) ─────────────
    result = {
        "full_version": full_version,
        "exe_name":     exe_name,
        "version":      version,
        "commit":       commit,
        "is_dev":       is_dev,
        "build":        build,
    }
    print(json.dumps(result))


if __name__ == "__main__":
    main()
