# AUTO-GENERATED by build_exe.ps1 -- do not edit manually.
# Built: DEV 0.0.1 build 10  commit 214b913
VERSION = "0.0.1"
BUILD = 10
COMMIT = "214b913"
IS_DEV = True
FULL_VERSION = "DEV 0.0.1 build 10"
